name: simulador_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-89.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: 4.8.1
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  dio: ^5.4.3+1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  slang_build_runner: ^3.29.0

flutter:
  uses-material-design: true